TAG = 'BALN'
TOKEN_NAME = 'Balance Token'
SYMBOL_NAME = 'BALN'
DEFAULT_ORACLE_NAME = 'Balanced DEX'

DEFAULT_DECIMAL_VALUE = 18
DEFAULT_INITIAL_SUPPLY = 0
DAY_TO_MICROSECOND = 86400 * 10 ** 6
EXA = 10 ** 18


class Status:
    AVAILABLE = 0
    STAKED = 1
    UNSTAKING = 2
    UNSTAKING_PERIOD = 3


MAX_LOOP = 100
INITIAL_PRICE_ESTIMATE = 10 ** 17  # loop
MIN_UPDATE_TIME = 2000000  # 2 seconds
MINIMUM_STAKE = 10 ** 18
DEFAULT_UNSTAKING_PERIOD = 3 * DAY_TO_MICROSECOND

IDS = "ids"
AMOUNT = "amount"
